<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>手写Promise_14_Promise下独立的方法_reject</title>
        <script src="./index.js"></script>
    </head>
    <body>
        <!-- 
            Promise下的reject方法不同于resolve方法
            reject方法是不受参数的影响，将始终返回一个失败的Promise实例对象
         -->
        <script>
            const pms1 = Promise.reject(1);
            console.log(pms1);

            const pms2 = Promise.reject(
                new Promise((resolve, reject) => {
                    resolve(2);
                })
            );
            console.log(pms2);

            const pms3 = Promise.reject(
                new Promise((resolve, reject) => {
                    reject(3);
                })
            );
            console.log(pms3);
        </script>
    </body>
</html>
